### ISSUE TITLE
1. 메인화면

### ISSUE THREAD

**Issue by YijiBae** [yjs03057/Getum#2]
- [x] 지도 ( 현재 우산함 위치)
- [x] 우산함 위치 (우산 개수- 아이콘에 개수 나타내기, 우산 사용 금액)
- [x] QR 코드 인식 버튼
- [x] 현재 위치 확인 버튼 
- [x] 툴바(사용자 관리 햄버거 버튼) 
- [x] 안내사항
- [x] 고객센터
